### ISSUE TITLE
Unexpected return value

### ISSUE THREAD

**Issue by boserup** [contentful/contentful-management.php#169]
Hello,

I have an issue, where an entry is unable to read it's own internal ID.
To me, this looks more like an internal issue with the SDK.

**Background info**
The entry has the class `ProductEntry`, which extends `Contentful\Management\Resource\Entry`. Upon requesting an entry with the SDK, it is autoatticly mapped to `ProductEntry` with a mapper, using the `setDataMapperMatcher` method on `ResourceBuilder`.

The `normalize` method in the last part of the stacktrace calls `getId()` on the Entry instance.

Maybe it's also worth mentioning that when we create entries using the SDK, we set the contentID to a numeric value, which in turn works fine.

**Stacktrace**
Here's the important part of the stacktrace:

```
Return value of Contentful\Management\Resource\Entry::getSystemProperties() must be an instance of Contentful\Management\SystemProperties\Entry, instance of Contentful\Core\Resource\ArraySystemProperties returned {"exception":"[object] (TypeError(code: 0): Return value of Contentful\\Management\\Resource\\Entry::getSystemProperties() must be an instance of Contentful\\Management\\SystemProperties\\Entry, instance of Contentful\\Core\\Resource\\ArraySystemProperties returned at /var/www/application/vendor/contentful/contentful-management/src/Resource/Entry.php:64)

[stacktrace]
#0 /var/www/application/vendor/contentful/contentful-management/src/Resource/BaseResource.php(39): Contentful\\Management\\Resource\\Entry->getSystemProperties()
#1 /var/www/application/src/app/Integrations/CMS/Contentful/Management/Entries/ProductEntry.php(50): Contentful\\Management\\Resource\\BaseResource->getId()
#2 /var/www/application/src/app/Integrations/CMS/ContentfulCMSProvider.php(112): App\\Integrations\\Contentful\\Management\\Entries\\ProductEntry->normalize()
```

**Comment by boserup** [comment]
Never mind - turned out to be an issue with hydrating the entry instance.
